In [1]:
import numpy as np
a = np.array([[1,2],
             [3,4]])

In [2]:
a(1,1)

TypeError: 'numpy.ndarray' object is not callable

In [3]:
a[1,1]

4

In [4]:
list(range(4))

[0, 1, 2, 3]

In [8]:
np.random.uniform()

0.8081790704955589

In [9]:
import pandas as pd

In [10]:
actions = list(range(4))

In [12]:
q_tabel = pd.DataFrame(columns=actions, dtype=np.float64)

In [13]:
q_tabel.index

Index([], dtype='object')

In [14]:
[0] *4

[0, 0, 0, 0]

In [18]:
q_tabel.append(pd.Series(
                    [0]*len(actions),
                    index=q_tabel.columns,
                    name='u',))

0    1    2    3
u  0.0  0.0  0.0  0.0

In [19]:
1 not 2

SyntaxError: invalid syntax (<ipython-input-19-e5571699e89e>, line 1)

In [20]:
1 != 2

True

In [21]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [22]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
b = np.array([1,2])

In [24]:
a(b)

TypeError: 'numpy.ndarray' object is not callable

In [25]:
a[b]

array([[4, 5, 6],
       [7, 8, 9]])

In [26]:
b

array([1, 2])

In [27]:
a[b[0],b[1]]

6

In [1]:
import numpy as np
end = np.array([6.7])

In [2]:
s = np.array([2,0])

In [5]:
if s[0] == end[0] and s[1] == end[1]:
    print('1')

In [4]:
(s == end).all

<function ndarray.all>

In [6]:
s[0] == end[0] and s[1] == end[1]

False

In [7]:
s is end

False

In [10]:
if s is end:
    print('1')

1


In [9]:
s = end

In [11]:
a = 1
b = a

In [12]:
b

1

In [13]:
a = 2

In [14]:
b

1

In [15]:
global a

In [16]:
b= a

In [17]:
b

2

In [18]:
a =3

In [19]:
a

3

In [20]:
b

2